import Head from "next/head";
import Link from "next/link";

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="p-10">
      <Link
        href="/document/button"
        className="inline-block  text-xl font-bold text-blue-500 no-underline hover:text-blue-700"
      >
        Buttonページへ
      </Link>
      <Link
        href="/document/layout/layout"
        className="inline-block  text-xl font-bold text-blue-500 no-underline hover:text-blue-700"
      >
        Layoutページへ
      </Link>
    </div>
  </>
);

export default Home;
