import { Grid } from "@mantine/core";
import Head from "next/head";
import Link from "next/link";

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Grid className="p-10" gutter={40} columns={10}>
      <Grid.Col span={2}>
        <Link
          href="/document/button"
          className="inline-block  text-xl font-bold text-blue-500 no-underline hover:text-blue-700"
        >
          Buttonページへ
        </Link>
      </Grid.Col>
      <Grid.Col span={2}>
        <Link
          href="/document/layout/layout"
          className="inline-block  text-xl font-bold text-blue-500 no-underline hover:text-blue-700"
        >
          Layoutページへ
        </Link>
      </Grid.Col>
      <Grid.Col span={2}>
        <Link
          href="/document/input/inputPage"
          className="inline-block  text-xl font-bold text-blue-500 no-underline hover:text-blue-700"
        >
          Inputページへ
        </Link>
      </Grid.Col>
    </Grid>
  </>
);

export default Home;
